### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by srhughes89** [beechatnetworkadmin/BeeChatNetwork#18]
I would like to try your Network out. Can you please guide me on how to compile it.

**Comment by BeechatNetworkSystemsLtd** [comment]
We are working on a very big update, at which point it will follow the traditional building convention. The new version will feature two parts: a server (for the radio hotspots based on Java) and a client app (QT-based). We recommend waiting for the release which will be released in the coming weeks!

**Comment by srhughes89** [comment]
Sounds good. I will try to wait patiently for it...😀
